package com.tlacuachesdevs.mydbms.gui;

import com.tlacuachesdevs.mydbms.managers.DataManager;
import com.tlacuachesdevs.mydbms.table.Tables;

/**
 *
 * @author mander
 */
public class DBMSJFrame extends javax.swing.JFrame {

    //Initialize Objects
    Tables tables = new Tables();
    DataManager dataManager = new DataManager();

    /**
     * Creates new form MainJFrame
     */
    public DBMSJFrame() {
        initComponents();
        this.setTitle("MyDBSMS");
        this.setLocationRelativeTo(null);
        dataManager.setTables(tables);
        dataManager.setXMLText(uploadXMLButton, xmlJTextArea);
        dataManager.setXMLText(uploadRecordsButton, recordsJTextArea);
        dataManager.setER(uploadERButton, imageViewerScrollPane);
        dataManager.readTables(sendTablesButton);
        dataManager.showTables(viewDBButton, databaseJTextArea);
        dataManager.sendRecords(sendRecordsButton);
        dataManager.showBPTrees(viewBPTreesButton, bptJTextArea, databaseJTextArea);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tablesJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xmlJTextArea = new javax.swing.JTextArea();
        uploadXMLButton = new javax.swing.JButton();
        sendTablesButton = new javax.swing.JButton();
        recordsJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recordsJTextArea = new javax.swing.JTextArea();
        uploadRecordsButton = new javax.swing.JButton();
        sendRecordsButton = new javax.swing.JButton();
        diagramsViewerPabel = new javax.swing.JPanel();
        uploadERButton = new javax.swing.JButton();
        imageViewerScrollPane = new javax.swing.JScrollPane();
        bptreeViewerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bptJTextArea = new javax.swing.JTextArea();
        viewBPTreesButton = new javax.swing.JButton();
        dataBasesPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        databaseJTextArea = new javax.swing.JTextArea();
        viewDBButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablesJPanel.setMaximumSize(new java.awt.Dimension(1138, 665));

        xmlJTextArea.setColumns(20);
        xmlJTextArea.setRows(5);
        xmlJTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        xmlJTextArea.setMaximumSize(new java.awt.Dimension(226, 91));
        jScrollPane1.setViewportView(xmlJTextArea);

        uploadXMLButton.setText("Upload XML");
        uploadXMLButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sendTablesButton.setText("Send Tables (DB)");
        sendTablesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout tablesJPanelLayout = new javax.swing.GroupLayout(tablesJPanel);
        tablesJPanel.setLayout(tablesJPanelLayout);
        tablesJPanelLayout.setHorizontalGroup(
            tablesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tablesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendTablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        tablesJPanelLayout.setVerticalGroup(
            tablesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tablesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(tablesJPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(uploadXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendTablesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Database Tables", tablesJPanel);

        recordsJPanel.setMaximumSize(new java.awt.Dimension(1138, 665));

        jScrollPane2.setMaximumSize(new java.awt.Dimension(228, 93));

        recordsJTextArea.setColumns(20);
        recordsJTextArea.setRows(5);
        recordsJTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(recordsJTextArea);

        uploadRecordsButton.setText("Upload XML");
        uploadRecordsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sendRecordsButton.setText("Send Records");
        sendRecordsButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout recordsJPanelLayout = new javax.swing.GroupLayout(recordsJPanel);
        recordsJPanel.setLayout(recordsJPanelLayout);
        recordsJPanelLayout.setHorizontalGroup(
            recordsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recordsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(recordsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        recordsJPanelLayout.setVerticalGroup(
            recordsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recordsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(recordsJPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(uploadRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Records", recordsJPanel);

        diagramsViewerPabel.setMaximumSize(new java.awt.Dimension(1138, 665));

        uploadERButton.setText("View Entity-Relation");
        uploadERButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout diagramsViewerPabelLayout = new javax.swing.GroupLayout(diagramsViewerPabel);
        diagramsViewerPabel.setLayout(diagramsViewerPabelLayout);
        diagramsViewerPabelLayout.setHorizontalGroup(
            diagramsViewerPabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagramsViewerPabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageViewerScrollPane)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diagramsViewerPabelLayout.createSequentialGroup()
                .addContainerGap(464, Short.MAX_VALUE)
                .addComponent(uploadERButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(450, 450, 450))
        );
        diagramsViewerPabelLayout.setVerticalGroup(
            diagramsViewerPabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diagramsViewerPabelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageViewerScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadERButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Diagrams Viewer", diagramsViewerPabel);

        bptreeViewerPanel.setMaximumSize(new java.awt.Dimension(1138, 665));

        jScrollPane3.setMaximumSize(new java.awt.Dimension(228, 93));

        bptJTextArea.setColumns(20);
        bptJTextArea.setRows(5);
        bptJTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(bptJTextArea);

        viewBPTreesButton.setText("View BPTrees");
        viewBPTreesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout bptreeViewerPanelLayout = new javax.swing.GroupLayout(bptreeViewerPanel);
        bptreeViewerPanel.setLayout(bptreeViewerPanelLayout);
        bptreeViewerPanelLayout.setHorizontalGroup(
            bptreeViewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bptreeViewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewBPTreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        bptreeViewerPanelLayout.setVerticalGroup(
            bptreeViewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bptreeViewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bptreeViewerPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(viewBPTreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BPT Viewer", bptreeViewerPanel);

        dataBasesPanel.setMaximumSize(new java.awt.Dimension(1138, 665));

        jScrollPane4.setMaximumSize(new java.awt.Dimension(228, 93));

        databaseJTextArea.setEditable(false);
        databaseJTextArea.setColumns(20);
        databaseJTextArea.setRows(5);
        databaseJTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane4.setViewportView(databaseJTextArea);

        viewDBButton.setText("View DB/Tables");
        viewDBButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout dataBasesPanelLayout = new javax.swing.GroupLayout(dataBasesPanel);
        dataBasesPanel.setLayout(dataBasesPanelLayout);
        dataBasesPanelLayout.setHorizontalGroup(
            dataBasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataBasesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        dataBasesPanelLayout.setVerticalGroup(
            dataBasesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataBasesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(dataBasesPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(viewDBButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tables/DB Viewer", dataBasesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("jTabbedPanel");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bptJTextArea;
    private javax.swing.JPanel bptreeViewerPanel;
    private javax.swing.JPanel dataBasesPanel;
    private javax.swing.JTextArea databaseJTextArea;
    private javax.swing.JPanel diagramsViewerPabel;
    private javax.swing.JScrollPane imageViewerScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel recordsJPanel;
    private javax.swing.JTextArea recordsJTextArea;
    private javax.swing.JButton sendRecordsButton;
    private javax.swing.JButton sendTablesButton;
    private javax.swing.JPanel tablesJPanel;
    private javax.swing.JButton uploadERButton;
    private javax.swing.JButton uploadRecordsButton;
    private javax.swing.JButton uploadXMLButton;
    private javax.swing.JButton viewBPTreesButton;
    private javax.swing.JButton viewDBButton;
    private javax.swing.JTextArea xmlJTextArea;
    // End of variables declaration//GEN-END:variables
}
