package com.tlacuachesdevs.mydbms.gui;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.tlacuachesdevs.mydbms.managers.DataManager;
import com.tlacuachesdevs.mydbms.managers.DataManager;
/**
 *
 * @author mander
 */
public class MainJFrame extends javax.swing.JFrame {

    //Initialize Objects
    DataManager dataManager = new DataManager();

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        this.setTitle("MyDBSMS");
        this.setLocationRelativeTo(null);
        dataManager.setBetsText(uploadXMLButton, xmlJTextArea);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        xmlJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xmlJTextArea = new javax.swing.JTextArea();
        uploadXMLButton = new javax.swing.JButton();
        sendXMLButton = new javax.swing.JButton();
        diagramsViewerPabel = new javax.swing.JPanel();
        viewERButton = new javax.swing.JButton();
        viewRelationalButton = new javax.swing.JButton();
        bptreeViewerPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        xmlJTextArea2 = new javax.swing.JTextArea();
        viewBPTreesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        xmlJTextArea.setColumns(20);
        xmlJTextArea.setRows(5);
        xmlJTextArea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(xmlJTextArea);

        uploadXMLButton.setText("Upload XML");
        uploadXMLButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        sendXMLButton.setText("Send XML");
        sendXMLButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout xmlJPanelLayout = new javax.swing.GroupLayout(xmlJPanel);
        xmlJPanel.setLayout(xmlJPanelLayout);
        xmlJPanelLayout.setHorizontalGroup(
            xmlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(xmlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(xmlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(uploadXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        xmlJPanelLayout.setVerticalGroup(
            xmlJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, xmlJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(xmlJPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(uploadXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sendXMLButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("XML", xmlJPanel);

        viewERButton.setText("View Entity-Relation");
        viewERButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        viewRelationalButton.setText("View Relational");
        viewRelationalButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout diagramsViewerPabelLayout = new javax.swing.GroupLayout(diagramsViewerPabel);
        diagramsViewerPabel.setLayout(diagramsViewerPabelLayout);
        diagramsViewerPabelLayout.setHorizontalGroup(
            diagramsViewerPabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagramsViewerPabelLayout.createSequentialGroup()
                .addContainerGap(904, Short.MAX_VALUE)
                .addGroup(diagramsViewerPabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewERButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewRelationalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
        diagramsViewerPabelLayout.setVerticalGroup(
            diagramsViewerPabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diagramsViewerPabelLayout.createSequentialGroup()
                .addContainerGap(200, Short.MAX_VALUE)
                .addComponent(viewRelationalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewERButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );

        jTabbedPane1.addTab("Diagrams Viewer", diagramsViewerPabel);

        xmlJTextArea2.setColumns(20);
        xmlJTextArea2.setRows(5);
        xmlJTextArea2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setViewportView(xmlJTextArea2);

        viewBPTreesButton.setText("View BPTrees");
        viewBPTreesButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout bptreeViewerPanelLayout = new javax.swing.GroupLayout(bptreeViewerPanel);
        bptreeViewerPanel.setLayout(bptreeViewerPanelLayout);
        bptreeViewerPanelLayout.setHorizontalGroup(
            bptreeViewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bptreeViewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewBPTreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        bptreeViewerPanelLayout.setVerticalGroup(
            bptreeViewerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bptreeViewerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bptreeViewerPanelLayout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(viewBPTreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BPT Viewer", bptreeViewerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("jTabbedPanel");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bptreeViewerPanel;
    private javax.swing.JPanel diagramsViewerPabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton sendXMLButton;
    private javax.swing.JButton uploadXMLButton;
    private javax.swing.JButton viewBPTreesButton;
    private javax.swing.JButton viewERButton;
    private javax.swing.JButton viewRelationalButton;
    private javax.swing.JPanel xmlJPanel;
    private javax.swing.JTextArea xmlJTextArea;
    private javax.swing.JTextArea xmlJTextArea2;
    // End of variables declaration//GEN-END:variables
}
